### PR TITLE
improvement(export): export function to processed DOM loaded after DOM ready

### PR DESCRIPTION
**Pull request by PikachuEXE**
Similar to #59 but with no tab -> space conversion 
This one does not update change log / version / minified JS
Also different to #59 the existing arguments is moved into the function as default arguments
Let me know what you think

### CODE REVIEW

**Comment by mfranzke** [comment]
@PikachuEXE, thanks a lot for your contribution !

I‘m mainly struggling with the Ie compatibility down to version 9, that I‘ve accomplished through not necessarily using the latest coolest features (which I would have liked to do so), but mainly written plain old stable JS.
I sadly as well don‘t have the experience with exports and modules etc., so I wouldn‘t be able to judge or lead to solutions that could probably fit for both needs.

What do you think about those aspects? Is there a simple path / solution to come up with compatibility but even also deliver on the needs of current JS tech features?
Elsewhere I would be able to do some research and get some knowledge on this whole topic during these days.

**Comment by PikachuEXE** [comment]
Not sure why I forgot UMD pattern
Applied and tested with IE 9
You can test by visiting
https://output.jsbin.com/yomocox

**Comment by julesrenaud** [comment]
@mfranzke I'm going to comment on this "issue" here, since the purpose of this pr is probably to make the polyfill work when images are added after the DOM is loaded (i.e. ajax). I was puzzled when I encountered this issue because an older website I worked on used 
loading-attribute-polyfill v1.1.0 and did not encounter this issue when images were ajaxed. I reverted to v1.1.0 from v1.5.3 on the website I'm currently working on and it solved the issue, the images are now being lazyloaded after being added to the DOM via ajax.

**Comment by mfranzke** [comment]
@PikachuEXE - sadly it took me a while to provide a solution. Do you have the chance to review my implementation provided with #96 ?

**Comment by PikachuEXE** [comment]
I am using another library right now
What should I do to review changes in #96 ?

**Comment by mfranzke** [comment]
@PikachuEXE I've released a beta version of this polyfill: [loading-attribute-polyfill@latest](https://www.npmjs.com/package/loading-attribute-polyfill) - if I could still motivate you to test it and if you're still able even that you're using another library right now (and hopefully I could motivate you to come back), that would be awesome.

**Comment by PikachuEXE** [comment]
I have done this
- Add `loading-attribute-polyfill@2.0.0-beta.1` to project
- Add following code to one of the existing JS files
```js
import loadingAttributePolyfill from "loading-attribute-polyfill"
window.loadingAttributePolyfill = loadingAttributePolyfil
```
- Run `loadingAttributePolyfill.prepareElement(document.querySelector('img'));` in browser to ensure the function exists & can be executed

**Comment by mfranzke** [comment]
@PikachuEXE , okay, thanks a lot.

**Pull request closed without merging**
